version: '3.8'
services:
  redis:
    image: redis:7.2
    container_name: trainup-redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trainup-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_REDIS_HOST=trainup-redis
    depends_on:
      - redis

