

spring:
  config:
    import:
      - optional:file:./.env[.properties]
      - optional:file:${user.dir}/.env[.properties]
      - optional:file:${user.dir}/../.env[.properties]

  app:
    frontend-url: ${APP_FRONTEND_URL:https://fe-trainup.vercel.app}
    cookie:
      secure: false
      same-site: Lax
      domain:
      access-name: portal_access_token
      refresh-name: portal_refresh_token


  application:
    name: ${SPRING_APPLICATION_NAME}

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
          starttls:
            enable: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}

  redis:
    host: ${SPRING_REDIS_HOST}
    port: ${SPRING_REDIS_PORT}
    timeout: ${SPRING_REDIS_TIMEOUT}
    database: ${SPRING_REDIS_DATABASE}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

cloud:
  aws:
    credentials:
      access-key: ${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
      secret-key: ${CLOUD_AWS_CREDENTIALS_SECRET_KEY}
    region:
      static: ${CLOUD_AWS_REGION_STATIC}
    s3:
      bucket: ${CLOUD_AWS_S3_BUCKET}
      presign-expiration-ms: 300000 # 5 phút

firebase:
  authentication:
    key:
      file: 'classpath:train-up-fireBase.json'

server:
  port: ${SERVER_PORT}

servlet:
  multipart:
    max-file-size: 20MB
    max-request-size: 20MB

# =============================
# SECURITY CONFIG (GIỮ TRONG YAML)
# =============================
security:
  cors:
    enabled: true
    allowed-origins: "*"
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: Authorization,Content-Type,X-Recovery-Token,X-Reset-Token


  public-urls:
    - /api/address/**
    - /api/products/**
    - /api/auth/**
    - /api/media/**
    - /api/categories/**
    - /api/orders/**
    - /api/payments/**
    - /api/reviews/**
    - /api/coupons/**
    - /api/chat/**
  protected-urls:
    - urlPattern: /api/carts/**
      roles: [ CUSTOMER, TRAINER, ADMIN ]
    - urlPattern: /api/users/**
      roles: [CUSTOMER, TRAINER, ADMIN]




discord:
  webhook-url: ${DISCORD_WEBHOOK_URL}

# =============================
# PAYOS CONFIG
# =============================
payos:
  client-id: ${PAYOS_CLIENT_ID}
  api-key: ${PAYOS_API_KEY}
  checksum-key: ${PAYOS_CHECKSUM_KEY}
  return-url: http://localhost:5173
  cancel-url: http://localhost:5173/order
