

spring:
  config:
    import:
      - optional:file:./.env[.properties]
      - optional:file:${user.dir}/.env[.properties]
      - optional:file:${user.dir}/../.env[.properties]

  app:
    cookie:
      secure: ${APP_COOKIE_SECURE:true}
      same-site: ${APP_COOKIE_SAME_SITE:None}
      domain:
      access-name: portal_access_token
      refresh-name: portal_refresh_token

  application:
    name: ${SPRING_APPLICATION_NAME:api-portal-service}

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/trainUp}

  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:true}

  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}
    timeout: ${SPRING_REDIS_TIMEOUT:6000}
    database: ${SPRING_REDIS_DATABASE:0}

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:86400000}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000}

cloud:
  aws:
    credentials:
      access-key: ${CLOUD_AWS_CREDENTIALS_ACCESS_KEY:}
      secret-key: ${CLOUD_AWS_CREDENTIALS_SECRET_KEY:}
    region:
      static: ${CLOUD_AWS_REGION_STATIC:ap-southeast-2}
    s3:
      bucket: ${CLOUD_AWS_S3_BUCKET:nqt-s3-demo}
      presign-expiration-ms: 300000 # 5 phút

firebase:
  authentication:
    key:
      file: 'classpath:train-up-fireBase.json'

server:
  port: ${PORT:8080}

servlet:
  multipart:
    max-file-size: 20MB
    max-request-size: 20MB

# =============================
# SECURITY CONFIG (GIỮ TRONG YAML)
# =============================
security:
  cors:
    enabled: true
    allowed-origins: "${SECURITY_CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:5174,http://localhost:3000,https://*.vercel.app}"
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
    allowed-headers: Authorization,Content-Type,X-Recovery-Token,X-Reset-Token


  public-urls:
    - /api/address/**
    - /api/products/**
    - /api/auth/**
    - /api/media/**
    - /api/categories/**
    - /api/orders/**
    - /api/payments/**
    - /api/reviews/**
    - /api/coupons/**
    - /api/chat/**
  protected-urls:
    - urlPattern: /api/carts/**
      roles: [ CUSTOMER, TRAINER, ADMIN ]
    - urlPattern: /api/users/**
      roles: [CUSTOMER, TRAINER, ADMIN]


discord:
  webhook-url: ${DISCORD_WEBHOOK_URL:}

# =============================
# PAYOS CONFIG
# =============================
payos:
  client-id: ${PAYOS_CLIENT_ID:}
  api-key: ${PAYOS_API_KEY:}
  checksum-key: ${PAYOS_CHECKSUM_KEY:}
  return-url: http://localhost:5173
  cancel-url: http://localhost:5173/order
